project:
  type: website

website:
  favicon: "images/logos/png tr/Logo Only.png"
  navbar:
    title: false
    logo: images/logos/png bl/Horizontal.png
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - talks.qmd
      - about.qmd
      - icon: github
        href: https://github.com/mattfarrow1
  page-footer: 
    background: light
    left: Copyright 2023, Matt Farrow
    right: This website is built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/)
format:
  html:
    theme: impactsignals.scss
    css: styles.css
    toc: true

editor: visual

